version: 2
jobs:
  build:
    docker:
      - image: circleci/php:7.3.0-node-browsers
      - image: circleci/mariadb:10.4
    environment:
      - DB_CONNECTION: circle_testing
    working_directory: ~/ci-demo
    steps:
      - checkout
      - run:
          name: Update apt-get
          command: |
            sudo apt-get update \
                   gcc \
                   make \
                   libpng-dev \
                   git \
                   unzip \
                   vim \
                   libmcrypt-dev \
                   mysql-client \
                   curl \
                   gnupg \
                   libjpeg-dev \
                   libfreetype6-dev 
                   sudo docker-php-ext-install mcrypt pdo_mysql mysqli mbstring zip 
                   sudo docker-php-ext-configure gd --with-freetype-dir=/usr/include/ --with-jpeg-dir=/usr/include/ 
                   sudo docker-php-ext-install -j$(nproc) gd
      - run:
          name: Install php-gd
          command: |
            sudo apt-get -y install libpng-dev
            sudo docker-php-ext-configure gd --with-freetype --with-jpeg
            sudo docker-php-ext-install gd

      - run:
          name: Docker php extensions install
          command: sudo docker-php-ext-install pdo_mysql
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "composer.json" }}
            - v1-dependencies-
      - run:
          name: Install PHP libraries
          command: composer install -n --prefer-dist
      - save_cache:
          paths:
            - ./vendor
          key: v1-dependencies-{{ checksum "composer.json" }}
      - run:
          name: Run PHPUnit
          command: vendor/bin/phpunit
